name: Publish notebooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: git remote set-url --push origin "https://:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        mkdir -p _build/html
        jupyter nbconvert --execute --to html --output-dir _build/html *.ipynb 
        ghp-import -n -p -f _build/html